### ISSUE TITLE
prismjs should be in production dependencies

### ISSUE THREAD

**Issue by cdauth** [tpadjen/ng2-prism#2]
Currently, the dependency to `prismjs` is in the `devDependencies`. As it is required for using ng2-prism, it should be in the `dependencies`. Otherwise, applications using ng2-prism need to depend on it  by hand.

In addition, the `require` statements in `src/code-renderer.component.ts` should use `prismjs/` instead of `prism/`, in order to match the npm dependency. Otherwise, users of ng2-prism have to not only add prismjs as a dependency, but also have to rename/symlink it to prism.

**Comment by tpadjen** [comment]
That's a good point. The bundled version of codeblock embedded the prismjs source, and the main import was loading the bundled version so everything worked out. Until you try to import from src.  I've fixed this by making prismjs a proper dependency and not relying on the bundled version with 32329bf. I pushed an update to the npm repository as well, version 2.2.1. This also closes #3.
